version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
      
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db  # Зависимость от базы данных PostgreSQL
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=policy_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password

  db:
    build:
      context: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: policy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: