version: '3'
services:
  frontend:
    image: yourdockerusername/frontend:latest
    ports:
      - "8080:80"
  backend:
    image: yourdockerusername/backend:latest
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: policy_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: policy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
