name: Build and Deploy to Docker Swarm

on:
  push:
    branches:
      - master  # Деплой будет запускаться на каждое обновление ветки `master`
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Запускать на Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонирование вашего репозитория

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Подготовка для сборки Docker

      - name: Cache Docker layers
        uses: actions/cache@v2  # Кэширование слоёв Docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build  # Сборка всех сервисов
          docker-compose -f docker-compose.yml push   # Отправка всех образов на Docker Hub

      - name: Deploy to Docker Swarm
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} user@yourserver "docker stack deploy -c docker-compose.yml my_stack"
